version: '3.8'

services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - trava-vol:/data/db

  frontend:
    container_name: dev_trava-frontend
    build: 
      context: ./frontend
      target: dev
    ports:
      - 80:5173
    volumes:
      - ./frontend/:/frontend
    restart: on-failure

  backend:
    container_name: dev_trava-backend
    build:
      context: ./backend
      target: dev
    env_file:
      - .dev.env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    restart: on-failure

volumes:
  trava-vol: